# Generated by Django 6.0.1 on 2026-01-18 12:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('default_shelf_life_days', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок хранения по умолчанию (дней)')),
                ('icon', models.CharField(default='fas fa-archive', max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('expiration_date', models.DateField(verbose_name='Срок годности до')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата покупки')),
                ('quantity', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество')),
                ('unit', models.CharField(choices=[('шт', 'шт'), ('кг', 'кг'), ('г', 'г'), ('л', 'л'), ('мл', 'мл'), ('уп', 'уп')], default='шт', max_length=10, verbose_name='Единица измерения')),
                ('storage', models.CharField(blank=True, choices=[('fridge', 'Холодильник'), ('freezer', 'Морозилка'), ('pantry', 'Кладовая'), ('room', 'Комнатная температура')], max_length=20, verbose_name='Место хранения')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет использования')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Примерная стоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('used', 'Использован'), ('expired', 'Просрочен'), ('thrown', 'Выброшен')], default='active', max_length=10, verbose_name='Статус')),
                ('notifications', models.BooleanField(default=True, verbose_name='Уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['expiration_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_expiry', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='За сколько дней до истечения срока')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст рекомендации')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='Текст действия')),
                ('icon', models.CharField(default='fas fa-lightbulb', max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Шаблон рекомендации',
                'verbose_name_plural': 'Шаблоны рекомендаций',
                'ordering': ['days_before_expiry'],
            },
        ),
    ]
